### ISSUE TITLE
Custom Launchpad Pro firmware isn't recognized properly

### ISSUE THREAD

**Issue by Shqrp** [nimaid/LPHK#17]
Hi Ella,

I wanted to try out LPHK with my Launchpad Pro, with a custom firmware installed on it (https://github.com/mat1jaczyyy/lpp-performance-cfw) and when I try to launch LPHK, it recognizes my LP as a Launchpad Classic/Mini/S and first of all, the layout is all messed up and the buttons don't do anything. I'm also encountering this error when first starting LPHK.
`Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Programmi\Miniconda3\envs\LPHK\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Programmi\Miniconda3\envs\LPHK\lib\threading.py", line 1177, in run
    self.function(*self.args, **self.kwargs)
  File "D:\Git Repositories\LPHK-master\lp_events.py", line 28, in run
    pressed[x][y] = False
IndexError: list index out of range`

I don't know what to do about it.

TheLifeGamingYT

**Comment by nimaid** [comment]
Have you ensured that your LP Pro is in `Live Mode`? https://github.com/mat1jaczyyy/lpp-performance-cfw#setup-mode

**Comment by duncte123** [comment]
Closing due to inactivity

**Comment by Still34** [comment]
I'm getting a similar issue. The layout and everything works, but the script would just randomly crash with the similar log stated above.

```

[files] Loaded layout C:/Users/Still/Documents/LPHK/user_layouts/layout.lpl
[lp_events] (1, 7) Unbound button...
Exception in thread Thread-733:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 1177, in run
  File "lp_events.py", line 28, in run
IndexError: list index out of range
```
