### ISSUE TITLE
Install hell on Linux

### ISSUE THREAD

**Issue by lyiriyah** [nimaid/LPHK#30]
@nimaid
OS: Ubuntu 18.04, fresh install. (Remember this)
PC: Thinkpad T430, i5 3320m, 16GB RAM, Samsung 256GB SSD
LP: LP MKII
Issue: I run the installer, it installs Conda fine. But when it tries to install LPHK, it doesn't create directories in ~/.conda and bitches to me that I don't have write permissions. I run as root, same issue. I run `chown lyiriyah .conda`. Still bitches. So I create the directories, change the ownership to me and run it again. It completes successfully. I run RUN.bash and it loads and doesn't detect my Launchpad. Happy fun. I am installing Conda myself as I write this, maybe that will change  something.

**Comment by lyiriyah** [comment]
Installed conda. When I run it it spits out `bash: /home/lyiriyah/miniconda3/bin/conda: No such file or directory`.

**Comment by lyiriyah** [comment]
Running conda install as root did nothing, am now installing miniconda3

**Comment by lyiriyah** [comment]
Conda works now!

**Comment by lyiriyah** [comment]
Same issue as before. I created ~/.conda/envs (maybe should be in script) and ran it. I'm going to run LPHK/RUN.bash, let's see what happens

**Comment by lyiriyah** [comment]
It launched!
Now something about ALSA, but I think that's mentioned in different issues (#5, #15). I'll install `libasound2-plugins`

**Comment by lyiriyah** [comment]
Installed it, but libasound2_module_conf_pulse.so doesn't exist anywhere (according to `sudo find / -name libasound2_module_conf_pulse.so` as suggested by @nimaid) If nimaid or @duncte123 could upload it that'd be great thanks

**Comment by lyiriyah** [comment]
@duncte123 @nimaid I got a different error! Log below:
---------------- BEGIN LOG 08/03/2020 15:34:22 ----------------
LPHK - LaunchPad HotKey - A Novation Launchpad Macro Scripting System
Version: 0.2.9
Platform: Linux
Is compiled executable: False
Is portable: True
Operating path: /home/lyiriyah/LPHK
User path: /home/lyiriyah/LPHK
Program file path: /home/lyiriyah/LPHK
Program file: /home/lyiriyah/LPHK/LPHK.py
Log file (this file): /home/lyiriyah/LPHK/LPHK.log

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

Traceback (most recent call last):
  File "/home/lyiriyah/LPHK/LPHK.py", line 85, in <module>
    import lp_events, scripts, kb, files, sound, window
  File "/home/lyiriyah/LPHK/lp_events.py", line 2, in <module>
    import lp_colors
  File "/home/lyiriyah/LPHK/lp_colors.py", line 4, in <module>
    import lp_events, scripts, window
  File "/home/lyiriyah/LPHK/scripts.py", line 4, in <module>
    import lp_events, lp_colors, kb, sound, ms
  File "/home/lyiriyah/LPHK/kb.py", line 2, in <module>
    import ms
  File "/home/lyiriyah/LPHK/ms.py", line 1, in <module>
    from pynput.mouse import Controller, Button
  File "/home/lyiriyah/.conda/envs/LPHK/lib/python3.7/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/lyiriyah/.conda/envs/LPHK/lib/python3.7/site-packages/pynput/keyboard/__init__.py", line 52, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/home/lyiriyah/.conda/envs/LPHK/lib/python3.7/site-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/home/lyiriyah/.conda/envs/LPHK/lib/python3.7/site-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/home/lyiriyah/.conda/envs/LPHK/lib/python3.7/site-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/home/lyiriyah/.conda/envs/LPHK/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/lyiriyah/.conda/envs/LPHK/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/lyiriyah/.conda/envs/LPHK/lib/python3.7/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'

**Comment by lyiriyah** [comment]
diff error diff issue. this one is fixed. issue closed.
